
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dev-space
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:17-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dev-space
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

# Mantiene i dati del database anche dopo il riavvio con il volume pgdata.
volumes:
  pgdata: